require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe ComponentFundsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # ComponentFund. As you add validations to ComponentFund, be sure to
  # adjust the attributes here as well.
  before(:each) do
    allow(controller).to receive(:authenticate_user!).and_return(true)
    @component = FactoryGirl.create(:component)
  end

  let(:valid_attributes) {
    {
      source: 1,
      amount: "9.99",
      component_id: @component.id
    }
  }

  let(:invalid_attributes) {
    {
      source: nil,
      amount: "9.99",
      component_id: nil
    }
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ComponentFundsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all component_funds as @component_funds" do
      component_fund = ComponentFund.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:component_funds)).to eq([component_fund])
    end
  end

  describe "GET #show" do
    it "assigns the requested component_fund as @component_fund" do
      component_fund = ComponentFund.create! valid_attributes
      get :show, {:id => component_fund.to_param}, valid_session
      expect(assigns(:component_fund)).to eq(component_fund)
    end
  end

  describe "GET #new" do
    it "assigns a new component_fund as @component_fund" do
      get :new, {}, valid_session
      expect(assigns(:component_fund)).to be_a_new(ComponentFund)
    end
  end

  describe "GET #edit" do
    it "assigns the requested component_fund as @component_fund" do
      component_fund = ComponentFund.create! valid_attributes
      get :edit, {:id => component_fund.to_param}, valid_session
      expect(assigns(:component_fund)).to eq(component_fund)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new ComponentFund" do
        expect {
          post :create, {:component_fund => valid_attributes}, valid_session
        }.to change(ComponentFund, :count).by(1)
      end

      it "assigns a newly created component_fund as @component_fund" do
        post :create, {:component_fund => valid_attributes}, valid_session
        expect(assigns(:component_fund)).to be_a(ComponentFund)
        expect(assigns(:component_fund)).to be_persisted
      end

      it "redirects to the created component_fund" do
        post :create, {:component_fund => valid_attributes}, valid_session
        expect(response).to redirect_to(ComponentFund.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved component_fund as @component_fund" do
        post :create, {:component_fund => invalid_attributes}, valid_session
        expect(assigns(:component_fund)).to be_a_new(ComponentFund)
      end

      it "re-renders the 'new' template" do
        post :create, {:component_fund => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        {
          source: 2,
          amount: "9.99",
          component_id: @component.id
        }
      }

      it "updates the requested component_fund" do
        component_fund = ComponentFund.create! valid_attributes
        put :update, {:id => component_fund.to_param, :component_fund => new_attributes}, valid_session
        component_fund.reload
        expect(assigns(:component_fund).source).to eq(new_attributes[:source])
      end

      it "assigns the requested component_fund as @component_fund" do
        component_fund = ComponentFund.create! valid_attributes
        put :update, {:id => component_fund.to_param, :component_fund => valid_attributes}, valid_session
        expect(assigns(:component_fund)).to eq(component_fund)
      end

      it "redirects to the component_fund" do
        component_fund = ComponentFund.create! valid_attributes
        put :update, {:id => component_fund.to_param, :component_fund => valid_attributes}, valid_session
        expect(response).to redirect_to(component_fund)
      end
    end

    context "with invalid params" do
      it "assigns the component_fund as @component_fund" do
        component_fund = ComponentFund.create! valid_attributes
        put :update, {:id => component_fund.to_param, :component_fund => invalid_attributes}, valid_session
        expect(assigns(:component_fund)).to eq(component_fund)
      end

      it "re-renders the 'edit' template" do
        component_fund = ComponentFund.create! valid_attributes
        put :update, {:id => component_fund.to_param, :component_fund => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested component_fund" do
      component_fund = ComponentFund.create! valid_attributes
      expect {
        delete :destroy, {:id => component_fund.to_param}, valid_session
      }.to change(ComponentFund, :count).by(-1)
    end

    it "redirects to the component_funds list" do
      component_fund = ComponentFund.create! valid_attributes
      delete :destroy, {:id => component_fund.to_param}, valid_session
      expect(response).to redirect_to(component_funds_url)
    end
  end

end
